export const NEXT_LAUNCH_FETCH_REQUESTED = 'NEXT_LAUNCH_FETCH_REQUESTED'
export const NEXT_LAUNCH_FETCH_SUCCEEDED = 'NEXT_LAUNCH_FETCH_SUCCEEDED'
export const NEXT_LAUNCH_FETCH_FAILED = 'NEXT_LAUNCH_FETCH_FAILED'

export const LATEST_LAUNCH_FETCH_REQUESTED = 'LATEST_LAUNCH_FETCH_REQUESTED'
export const LATEST_LAUNCH_FETCH_SUCCEEDED = 'LATEST_LAUNCH_FETCH_SUCCEEDED'
export const LATEST_LAUNCH_FETCH_FAILED = 'LATEST_LAUNCH_FETCH_FAILED'
