export const PLAYER_REACTED = 'PLAYER_REACTED'
export const PLAYER_READY = 'PLAYER_READY'
export const START_GAME = 'START_GAME'
export const START_ROUND = 'START_ROUND'
export const REVEAL_ROUND = 'REVEAL_ROUND'
export const END_ROUND = 'END_ROUND'
