export const LATEST_LAUNCH_FETCH_REQUESTED = 'LATEST_LAUNCH_FETCH_REQUESTED'
export const LATEST_LAUNCH_FETCH_SUCCEEDED = 'LATEST_LAUNCH_FETCH_SUCCEEDED'
export const LATEST_LAUNCH_FETCH_FAILED = 'LATEST_LAUNCH_FETCH_FAILED'
